autodetection for 1.5 and jrockit [ plz test on mac ]

diff --git a/aspectwerkz3/bin/aspectwerkz b/aspectwerkz3/bin/aspectwerkz
--- a/aspectwerkz3/bin/aspectwerkz
+++ b/aspectwerkz3/bin/aspectwerkz
@@ -45,17 +45,25 @@ if [ "$1" != "-offline" ]; then
     # -Daspectwerkz.classloader.wait=10 to delay connection (launching VM)
     # -Djavax.xml.parsers.SAXParserFactory=com.bluecast.xml.JAXPSAXParserFactory for java 1.3 [see FAQ, after ProcessStarter]
     
+    # -- J2SE 5 auto detection
+    $JAVA_COMMAND -cp $ASPECTWERKZ_HOME/lib/aspectwerkz-$ASPECTWERKZ_VERSION.jar org.codehaus.aspectwerkz.util.EnvironmentDetect -java
+    if [ $? -eq 15 ]; then
+        # -- Use for Java 1.5 --
+        # Note: all jars could be in regular classpath but this command line tool needs to support extra -cp arguments.
+        # FIXME: This is bad practice on 1.5 and can make CflowAspect fails.
+        # Note: For J2SE 5 prior to beta3b60, you must use -javaagent:org.codehaus.aspectwerkz.hook.Agent
+        $JAVA_COMMAND -javaagent:$ASPECTWERKZ_HOME/lib/aspectwerkz-core-$ASPECTWERKZ_VERSION.jar -Xbootclasspath/p:"$ASPECTWERKZ_HOME/lib/javassist-3.0beta.jar:$ASPECTWERKZ_HOME/lib/aspectwerkz-core-$ASPECTWERKZ_VERSION.jar:$ASPECTWERKZ_HOME/lib/aspectwerkz-$ASPECTWERKZ_VERSION.jar;$ASPECTWERKZ_LIBS" -Daspectwerkz.home="$ASPECTWERKZ_HOME" "$@"
+    fi
+
+    # -- JRockit (1.3 / 1.4) auto detection
+    $JAVA_COMMAND -cp $ASPECTWERKZ_HOME/lib/aspectwerkz-$ASPECTWERKZ_VERSION.jar org.codehaus.aspectwerkz.util.EnvironmentDetect -jvm
+    if [ $? -eq 2 ]; then
+        # -- Use for BEA JRockit --
+        $JAVA_COMMAND -Xmanagement:class=org.codehaus.aspectwerkz.extension.jrockit.JRockitPreProcessor -Xbootclasspath/p:"$ASPECTWERKZ_HOME/lib/aspectwerkz-extensions-$ASPECTWERKZ_VERSION.jar:$ASPECTWERKZ_HOME/lib/javassist-3.0beta.jar:$ASPECTWERKZ_HOME/lib/aspectwerkz-core-$ASPECTWERKZ_VERSION.jar:$ASPECTWERKZ_HOME/lib/aspectwerkz-$ASPECTWERKZ_VERSION.jar:$ASPECTWERKZ_LIBS" -Daspectwerkz.home="$ASPECTWERKZ_HOME" "$@"
+    fi
+
     # -- Use for Sun HotSpot and IBM JRE --
     $JAVA_COMMAND -cp $JAVA_HOME/lib/tools.jar:$ASPECTWERKZ_HOME/lib/javassist-3.0beta.jar:$ASPECTWERKZ_HOME/lib/aspectwerkz-core-$ASPECTWERKZ_VERSION.jar org.codehaus.aspectwerkz.hook.ProcessStarter -Xbootclasspath/p:"$ASPECTWERKZ_HOME/lib/javassist-3.0beta.jar:$ASPECTWERKZ_HOME/lib/aspectwerkz-core-$ASPECTWERKZ_VERSION.jar" -cp $CLASSPATH -cp $ASPECTWERKZ_HOME/lib/aspectwerkz-$ASPECTWERKZ_VERSION.jar:$ASPECTWERKZ_LIBS -Daspectwerkz.home=$ASPECTWERKZ_HOME "$@"
-    
-    # -- Use for BEA JRockit --
-    # $JAVA_COMMAND -Xmanagement:class=org.codehaus.aspectwerkz.extension.jrockit.JRockitPreProcessor -Xbootclasspath/p:"$ASPECTWERKZ_HOME/lib/aspectwerkz-extensions-$ASPECTWERKZ_VERSION.jar:$ASPECTWERKZ_HOME/lib/javassist-3.0beta.jar:$ASPECTWERKZ_HOME/lib/aspectwerkz-core-$ASPECTWERKZ_VERSION.jar:$ASPECTWERKZ_HOME/lib/aspectwerkz-$ASPECTWERKZ_VERSION.jar:$ASPECTWERKZ_LIBS" -Daspectwerkz.home="$ASPECTWERKZ_HOME" "$@"
-    
-    # -- Use for Java 1.5 --
-    # Note: all jars could be in regular classpath but this command line tool needs to support extra -cp arguments.
-    # FIXME: This is bad practice on 1.5 and can make CflowAspect fails.
-    # Note: For J2SE 5 prior to beta3b60, you must use -javaagent:org.codehaus.aspectwerkz.hook.Agent
-    # $JAVA_COMMAND -javaagent:$ASPECTWERKZ_HOME/lib/aspectwerkz-core-$ASPECTWERKZ_VERSION.jar -Xbootclasspath/p:"$ASPECTWERKZ_HOME/lib/javassist-3.0beta.jar:$ASPECTWERKZ_HOME/lib/aspectwerkz-core-$ASPECTWERKZ_VERSION.jar:$ASPECTWERKZ_HOME/lib/aspectwerkz-$ASPECTWERKZ_VERSION.jar;$ASPECTWERKZ_LIBS" -Daspectwerkz.home="$ASPECTWERKZ_HOME" "$@"
 
 else
     if [ "$#" -le 3 ]; then
